name: CI/CD Pipeline CYNA

on:
  push:
    branches:
      - master

jobs:
  # ------------------------
  # 1. Linting
  # ------------------------
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Lint Terraform
      - name: Lint Terraform
        run: terraform fmt -check ./04-devops/terraform

      # Lint Ansible
      - name: Lint Ansible
        run: ansible-lint ./04-devops/02-ansible/playbooks/configure_azure.yml

  # ------------------------
  # 2. Tests unitaires
  # ------------------------
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Terraform Tests (Terratest)
      - name: Terraform Test
        run: terratest -dir ./04-devops/terraform

      # Ansible Tests (Molecule)
      - name: Ansible Test
        run: cd ./04-devops/02-ansible && molecule test

  # ------------------------
  # 3. Déploiement
  # ------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3

      # Connexion à Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Terraform Init
      - name: Terraform Init
        run: terraform -chdir=./04-devops/terraform init -backend-config=backend.tfvars

      # Terraform Plan
      - name: Terraform Plan
        run: terraform -chdir=./04-devops/terraform plan -var-file=terraform.tfvars

      # Terraform Apply
      - name: Terraform Apply
        run: terraform -chdir=./04-devops/terraform apply -auto-approve -var-file=terraform.tfvars

      # Exécution du playbook Ansible
      - name: Run Ansible Playbook
        run: ansible-playbook -i ./04-devops/02-ansible/inventory/azure ./04-devops/02-ansible/playbooks/configure_azure.yml
